channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=23.0.1
- pip:
  - mlflow
  - pandas==1.2.4
  - cloudpickle==2.1.0
  - psutil==5.9.0
  - scikit-learn==1.0.2
  - typing-extensions==4.5.0
  - xgboost==1.5.2
name: mlflow-env
